### PR TITLE
Updating rpio version to allow Raspberry Pi 4 models to use this library!

### PR DESCRIPTION
**Pull request by bowdi**
It would be great to use this module with newer raspberry pi's, updating rpio doesn't seem to have any affects to this module.

### CODE REVIEW

**Comment by Mrtenz** [comment]
I don't have access to a Raspberry Pi currently to test this change, can you confirm that this does not break any functionality?

**Comment by bowdi** [comment]
It init's just fine, i've used the canvas: clear, text, line, fill and rectangle without issue on a RPI 4 2GB on node 11.15.0/Raspbian 5.4.72-v71+. Would you like anything else tested?

**Comment by Mrtenz** [comment]
That's great, thank you. I will deploy to npm tomorrow.

**Comment by bowdi** [comment]
Hi @Mrtenz, any news on the npm deploy?

**Comment by Mrtenz** [comment]
Sorry, I forgot... Just deployed it as [`sh1106@1.1.0`](https://www.npmjs.com/package/sh1106/v/1.1.0)

**Comment by bowdi** [comment]
Thanks!

**Pull request merged**
